FORMAT: 1A
HOST: http://fhee.kaist.ac.kr

# Food Hazard Events

An endpoint to access food hazard event information extracted from various sources (e.g. News, SNS)

## Events Collection [/events{?page,limit,after}]

### List of All Events [GET]

+ Parameters
    + page (number, optional) - parameter for pagination. The first page is returned if not specified.
    + limit (number, optional) - default is 20
    + after: `2016-12-09T06:12:08.000Z` (datetime, optional) - fetch events no later than the given datetime. The string should be in ISO8601 format.
    
+ Response 200 (application/json)
    
    + Attributes
        
        + events: Event (array[Event], required) - list of events
        + count: 1000 (number, required) - total count of events
        + page: 1 (number, required) - the current page
        + limit: 20 (number, required) - the current page limit

## Event [/events/{uid}/]

### Single Event [GET]

+ Parameters
    + uid: 256772 (integer, required) - event's unique id
    
+ Response 200 (application/json)
    te
    + Attributes (Event)
        
## Data Structures
### Event
+ uid: 1 - unique id (required)
+ created_at: 2016-12-09T06:12:08.000Z - the creation datetime of the original data
+ analyzed_at: 2016-12-09T06:12:08.000Z - the datetime of the analysis
+ media: 중앙일보 - the news media
+ text - information comming from source text
    + title - the title of source text
    + processed - the processed source text
+ keywords - food-hazard-related keywords extracted from the text
    + food (array[string]) - a food name keywords
    + ing (array[string]) - an ingredient keyword keywords
    + bio (array[string]) - a biological threat keywords
    + chem (array[string]) - a chemical threat keywords
    + germ (array[string])
    + city (array[string]) - city name keywords
    + county (array[string]) - keywords of geographical region in a city